name: 'Terraform Workflow Dispatch'

on:
  workflow_dispatch:
    inputs:
      terraform_operation:
        description: "Terraform operation: plan, apply, destroy"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - test
          - destroy

jobs:
  reusable-env-vars:
    runs-on: ubuntu-latest
    outputs:
      TF_VAR_GITHUB_REPOSITORY_OWNER: "${{ steps.env_variables.outputs.TF_VAR_GITHUB_REPOSITORY_OWNER }}"
      TF_VAR_GITHUB_REPOSITORY: "${{ steps.env_variables.outputs.TF_VAR_GITHUB_REPOSITORY }}"
      TF_VAR_GITHUB_REF: "${{ steps.env_variables.outputs.TF_VAR_GITHUB_REF }}"
      TF_VAR_GITHUB_ENV: "${{ steps.env_variables.outputs.TF_VAR_GITHUB_ENV }}"
    steps:
      - name: Encode Environment Variables
        id: env_variables
        env:
          TF_VAR_GITHUB_REPOSITORY_OWNER: "${{ github.repository_owner }}"
          TF_VAR_GITHUB_REPOSITORY: "${{ github.repository }}"
          TF_VAR_GITHUB_REF: "${{ github.ref }}"
          TF_VAR_GITHUB_ENV: production
        run: |
          echo "TF_VAR_GITHUB_REPOSITORY_OWNER=$(echo $TF_VAR_GITHUB_REPOSITORY_OWNER | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "TF_VAR_GITHUB_REPOSITORY=$(echo $TF_VAR_GITHUB_REPOSITORY | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "TF_VAR_GITHUB_REF=$(echo $TF_VAR_GITHUB_REF | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "TF_VAR_GITHUB_ENV=$(echo $TF_VAR_GITHUB_ENV | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
  
  terraform-dispatch-plan-0:
    needs: [ reusable-env-vars ]
    uses: sim-parables/github-workflows-reusable/.github/workflows/tf-dispatch-plan.yml@AzureDatabricksV1
    secrets:
      AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_DATABRICKS_ACCOUNT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET }}
      AZURE_DATABRICKS_ACCOUNT_SCIM_TOKEN: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_SCIM_TOKEN }}
      env_variables: |
        TF_VAR_GITHUB_REPOSITORY_OWNER="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY_OWNER }}"
        TF_VAR_GITHUB_REPOSITORY="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY }}"
        TF_VAR_GITHUB_REF="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REF }}"
        TF_VAR_GITHUB_ENV="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_ENV }}"
    with:
      ACT_MODE: ${{ !!github.event.act }}
      DATABRICKS_ADMINISTRATOR: "${{ vars.DATABRICKS_ADMINISTRATOR }}"
      working_directory: ./test/service_account
  
  terraform-dispatch-plan:
    if: "${{ github.event.act || github.event.inputs.terraform_operation == 'plan' }}"
    needs: [ reusable-env-vars, terraform-dispatch-plan-0 ]
    uses: sim-parables/github-workflows-reusable/.github/workflows/tf-dispatch-plan.yml@AzureDatabricksV1
    secrets:
      AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_DATABRICKS_ACCOUNT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET }}
      env_variables: |
        TF_VAR_SECURITY_GROUP_ID="00000000-0000-0000-0000-000000000000"
        TF_VAR_GITHUB_REPOSITORY_OWNER="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY_OWNER }}"
        TF_VAR_GITHUB_REPOSITORY="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY }}"
        TF_VAR_GITHUB_REF="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REF }}"
        TF_VAR_GITHUB_ENV="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_ENV }}"
    with:
      ACT_MODE: ${{ !!github.event.act }}
      DATABRICKS_ADMINISTRATOR: "${{ vars.DATABRICKS_ADMINISTRATOR }}"
      working_directory: ./test/databricks
      
  terraform-dispatch-auth:
    needs: [ reusable-env-vars ]
    uses: sim-parables/github-workflows-reusable/.github/workflows/tf-reusable-auth.yml@AzureDatabricksV1
    secrets:
      AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_DATABRICKS_ACCOUNT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_ID }}
      AZURE_DATABRICKS_ACCOUNT_SCIM_TOKEN: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_SCIM_TOKEN }}
      env_variables: |
        TF_VAR_GITHUB_REPOSITORY_OWNER="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY_OWNER }}"
        TF_VAR_GITHUB_REPOSITORY="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY }}"
        TF_VAR_GITHUB_REF="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REF }}"
        TF_VAR_GITHUB_ENV="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_ENV }}"
    with:
      ACT_MODE: ${{ !!github.event.act }}
      working_directory: ./test/service_account
  
  terraform-dispatch-auth-decode:
    needs: [ terraform-dispatch-auth ]
    name: Terraform Output
    runs-on: ubuntu-latest

    outputs:
      AZURE_CLIENT_ID: ${{ steps.decode.outputs.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ steps.decode.outputs.AZURE_CLIENT_SECRET }}
    
    steps:
      - id: decode
        run: |
          echo "::add-mask::$(echo "${{ needs.terraform-dispatch-auth.outputs.AZURE_CLIENT_SECRET }}" | base64 -di | base64 -di )"
          if ${{ !!github.event.act }}
          then
            echo "AZURE_CLIENT_SECRET=$(echo "${{ needs.terraform-dispatch-auth.outputs.AZURE_CLIENT_SECRET }}" | base64 -di | base64 -di )" >> $GITHUB_OUTPUT
          fi
          echo "AZURE_CLIENT_ID=$(echo "${{ needs.terraform-dispatch-auth.outputs.AZURE_CLIENT_ID }}" | base64 -di | base64 -di )" >> $GITHUB_OUTPUT

  terraform-dispatch-apply:
    if: ${{ github.event.act ||github.event.inputs.terraform_operation == 'apply' }}
    needs: [ reusable-env-vars, terraform-dispatch-auth, terraform-dispatch-auth-decode ]
    uses: sim-parables/github-workflows-reusable/.github/workflows/tf-dispatch-apply.yml@AzureDatabricksV1
    secrets:
      AZURE_CLIENT_ID: "${{ needs.terraform-dispatch-auth-decode.outputs.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: "${{ needs.terraform-dispatch-auth-decode.outputs.AZURE_CLIENT_SECRET }}"
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_DATABRICKS_ACCOUNT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET }}
      env_variables: |
        TF_VAR_SECURITY_GROUP_ID="${{ needs.terraform-dispatch-auth.outputs.SECURITY_GROUP_ID }}"
        TF_VAR_DATABRICKS_ADMINISTRATOR="${{ vars.ADMINISTRATOR_EMAIL }}"
        TF_VAR_GITHUB_REPOSITORY_OWNER="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY_OWNER }}"
        TF_VAR_GITHUB_REPOSITORY="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY }}"
        TF_VAR_GITHUB_REF="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REF }}"
        TF_VAR_GITHUB_ENV="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_ENV }}"
    with:
      ACT_MODE: ${{ !!github.event.act }}
      DATABRICKS_ADMINISTRATOR: "${{ vars.DATABRICKS_ADMINISTRATOR }}"
      working_directory: ./test/databricks
  
  terraform-dispatch-test:
    if: ${{ github.event.act || github.event.inputs.terraform_operation == 'test' }}
    needs: [ reusable-env-vars, terraform-dispatch-auth, terraform-dispatch-auth-decode ]
    uses: .github/workflows/reusable-test.yml
    secrets:
      AZURE_CLIENT_ID: "${{ needs.terraform-dispatch-auth-decode.outputs.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: "${{ needs.terraform-dispatch-auth-decode.outputs.AZURE_CLIENT_SECRET }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      ACT_MODE: ${{ !!github.event.act }}
      working_directory: ./test/databricks
      markers: ${{ !!github.event.act && 'github and client_credentials' || 'github and oidc'}}

  terraform-dispatch-destroy-0:
    needs: [ reusable-env-vars, terraform-dispatch-auth, terraform-dispatch-auth-decode ]
    uses: sim-parables/github-workflows-reusable/.github/workflows/tf-dispatch-destroy.yml@AzureDatabricksV1
    secrets:
      AZURE_CLIENT_ID: "${{ needs.terraform-dispatch-auth-decode.outputs.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: "${{ needs.terraform-dispatch-auth-decode.outputs.AZURE_CLIENT_SECRET }}"
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AZURE_DATABRICKS_ACCOUNT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_ID: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_ID }}
      AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET: ${{ secrets.AZURE_DATABRICKS_ACCOUNT_CLIENT_SECRET }}
      env_variables: |
        TF_VAR_SECURITY_GROUP_ID="${{ needs.terraform-dispatch-auth.outputs.TF_VAR_SECURITY_GROUP_ID }}"
        TF_VAR_GITHUB_REPOSITORY_OWNER="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY_OWNER }}"
        TF_VAR_GITHUB_REPOSITORY="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY }}"
        TF_VAR_GITHUB_REF="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REF }}"
        TF_VAR_GITHUB_ENV="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_ENV }}"
    with:
      ACT_MODE: ${{ !!github.event.act }}
      working_directory: ./test/databricks

  terraform-dispatch-destroy:
    if: ${{ github.event.act ||github.event.inputs.terraform_operation == 'destroy' }}
    needs: [ reusable-env-vars, terraform-dispatch-destroy-0 ]
    uses: sim-parables/github-workflows-reusable/.github/workflows/tf-dispatch-destroy.yml@AzureV1
    secrets:
      AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      env_variables: |
        TF_VAR_GITHUB_REPOSITORY_OWNER="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY_OWNER }}"
        TF_VAR_GITHUB_REPOSITORY="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REPOSITORY }}"
        TF_VAR_GITHUB_REF="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_REF }}"
        TF_VAR_GITHUB_ENV="${{ needs.reusable-env-vars.outputs.TF_VAR_GITHUB_ENV }}"
    with:
      ACT_MODE: ${{ !!github.event.act }}
      working_directory: ./test/service_account

